- name: Ensure apt cache is up to date
  apt:
    update_cache: yes

- name: Install necessary dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
    filename: docker

- name: Install Docker
  apt:
    name: docker-ce
    state: present

- name: Add Kubernetes apt-key
  get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    mode: "0644"

- name: Add Kubernetes repository
  apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /
    state: present

- name: Ensure apt cache is up to date
  apt:
    update_cache: yes

- name: Install Kubernetes components
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Hold Kubernetes packages at their current version
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    mark_hold: yes

- name: Enable and start Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Enable and start kubelet
  systemd:
    name: kubelet
    enabled: yes
    state: started

# - name: Initialize Kubernetes master node
#   # hosts: master
#   become: yes
# tasks:
- name: Initialize Kubernetes cluster
  command: kubeadm init --pod-network-cidr=10.0.0.0/16
  become: yes
  register: kubeadm_init
  ignore_errors: yes

- name: Set up kubeconfig for the root user
  command: "{{ item }}"
  become: yes
  with_items:
    - mkdir -p $HOME/.kube
    - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    - chown $(id -u):$(id -g) $HOME/.kube/config

- name: Install Calico network plugin
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  become: yes
