# - name: Add a new user
#   user:
#     name: "kubeuser"
#     comment: "kubeuser"
#     group: "users"
#     shell: "/bin/bash"
#     password: "{{ 'password' | password_hash('sha512') }}"
#     state: present
#
# - name: Create a home directory for the new user
#   file:
#     path: "/home/newusername"
#     state: directory
#     owner: "kubeuser"
#     group: "users"
#     mode: "0755"
#
# - name: Add the user to the sudo group
#   user:
#     name: "kubeuser"
#     groups: "sudo"
#     append: yes
#
# - name: Allow passwordless sudo for the new user (optional)
#   lineinfile:
#     path: /etc/sudoers
#     state: present
#     regexp: "^%kubeuser ALL="
#     line: "kubeuser ALL=(ALL) NOPASSWD:ALL"
#     validate: "visudo -cf %s"

- name: Ensure apt cache is up to date
  apt:
    update_cache: yes

- name: Install necessary dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
      - software-properties-common
    state: present

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
    filename: docker

- name: Install Docker
  apt:
    name: docker-ce
    state: present

- name: Add Kubernetes apt-key
  shell: |
    sudo mkdir -p -m 755 /etc/apt/keyrings
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes repository
  shell: |
    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: Ensure apt cache is up to date
  apt:
    update_cache: yes

- name: Install Kubernetes components
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Hold Kubernetes packages at their current version
  shell: |
    apt-mark hold kubelet kubeadm kubectl

- name: Enable and start Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Enable and start kubelet
  systemd:
    name: kubelet
    enabled: yes
    state: started

# - name: Initialize Kubernetes master node
#   # hosts: master
#   become: yes
# tasks:
- name: Restart Container.d service
  shell: |
    rm -f /etc/containerd/config.toml
    systemctl restart containerd

- name: Initialize Kubernetes cluster
  command: kubeadm init --pod-network-cidr=10.0.0.0/16
  register: kubeadm_init
  ignore_errors: yes

- name: Set up kubeconfig for the root user
  command: "{{ item }}"
  with_items:
    - sudo mkdir -p $HOME/.kube
    - sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
# - name: Update kube folder permission
#   folder:
#     path: $HOME/.kube
#     owner: kubeuser
#     group: root

- name: Install Calico network plugin
  command: curl https://docs.projectcalico.org/manifests/calico.yaml
  command: kubectl -f callico.yaml
