- name: Ensure apt cache is up to date
  apt:
    update_cache: yes

- name: Install necessary dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
      - software-properties-common
    state: present

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
    filename: docker

- name: Install Docker
  apt:
    name: docker-ce
    state: present

- name: Add Kubernetes apt-key
  shell: |
    sudo mkdir -p -m 755 /etc/apt/keyrings
    rm /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes repository
  shell: |
    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: Ensure apt cache is up to date
  apt:
    update_cache: yes

- name: Install Kubernetes components
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Hold Kubernetes packages at their current version
  shell: |
    apt-mark hold kubelet kubeadm kubectl

- name: Enable and start Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Enable and start kubelet
  systemd:
    name: kubelet
    enabled: yes
    state: started

- name: Restart Container.d service
  shell: |
    rm -f /etc/containerd/config.toml
    systemctl restart containerd

- name: Initialize Kubernetes cluster
  command: kubeadm init --pod-network-cidr=10.0.0.0/16
  register: kubeadm_init
  ignore_errors: yes

- name: Set up kubeconfig for the root user
  command: "{{ item }}"
  with_items:
    - sudo mkdir -p $HOME/.kube
    - sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
- name: connection refused problem solution
  command: swapoff -a

- name: connection refused problem solution
  command: strace -eopenat kubectl version
